### ISSUE TITLE
Medium bases are falling through the world again

### ISSUE THREAD

**Issue by TLFJ** [JohnnyCheese/TTS_XWing2#1]
Hi!

The newest update with the 2.0 fast builds to the right has the same fall-through-the-board issue as previously reported (you know where).

**Comment by JohnnyCheese** [comment]
Yeah, more people reported that issue.. I tried to fix the broken link several times, but only today (hopefully) I managed to sort it out! Please report if the issue continue to show up!

**Comment by TLFJ** [comment]
Running it as you typed this - it's currently working again!

**Comment by JohnnyCheese** [comment]
Awesome!
